### ISSUE TITLE
Update to current version of kfrlib

### ISSUE THREAD

**Issue by amundson** [kfrlib/fft-benchmark#1]
The version of fft-benchmark does not compile with the current version of kfrlib. Actually, it doesn't compile with any tagged release of kfrlib, as far as I can tell. It would be great to actually be able to run the benchmark!

**Comment by dancasarin** [comment]
The code updated to the version that was used for the latest benchmarks.

README.md is also updated.

**Comment by amundson** [comment]
Great! Thanks. I was able to get the benchmark working now.
---
James Amundson
Head, Scientific Computing Division

Office of the CIO
Fermi National Accelerator Laboratory
+1 (630) 840-2430 office
+1 (630) 488-6910 mobile

On Dec 4, 2018, at 10:46 AM, Dan Levin <notifications@github.com<mailto:notifications@github.com>> wrote:


The code updated to the version that was used for the latest benchmarks.

README.md is also updated.
