### ISSUE TITLE
Input possibly not being used?

### ISSUE THREAD

**Issue by geraintluff** [kfrlib/fft-benchmark#3]
I came across this line:

https://github.com/kfrlib/fft-benchmark/blob/d3a260c828879a0b8c13c6940b5ad24f41e1d086/fft_benchmark.cpp#L43

This looks odd - should it be `fft(size, out, in)`?

**Comment by dancasarin** [comment]
Hi,

The line you cited means that the benchmark tests inplace FFT.
Data is copied to `out` buffer in the previous line.
Full code:
https://github.com/kfrlib/fft-benchmark/blob/d3a260c828879a0b8c13c6940b5ad24f41e1d086/fft_benchmark.cpp#L39-L45
Then the same pointer is passed as both `in` and `out`.
All libraries used in benchmark (KFR, IPP and FFTW 3+) support this and do inplace FFT in that case.
