### ISSUE TITLE
Running FFT benchmarks

### ISSUE THREAD

**Issue by madhu-sudhan** [kfrlib/fft-benchmark#5]
Hello Team,

I have an issue while running the FFT benchmarks which is benchmarks.py. I have done the following steps and built the libraries.

make -Ipath_to_kfr/include -lkfr_dft -lkfr_io -j

After that, I see that we have to place headers like fftw3.h in the "include" directory. But I do not see the files present in your repository. Can you please confirm if I have to take them from the FFTW project?

Also I see below error when I run the benchmarks.py. Can you please confirm if there is any need for modification to get rid of below error. 

madhu@localhost:~/madhu/kfr/kfr/build/fft-benchmark$ python3 benchmark.py
primes_float_17_119 ...
/home/localhost/madhu/kfr/kfr/build/fft-benchmark/bin/fft_benchmark_kfr_float ...
Traceback (most recent call last):
  File "/home/localhost/madhu/kfr/kfr/build/fft-benchmark/benchmark.py", line 108, in <module>
    collect_data('primes', primes, 'float')
  File "/home/localhost/madhu/kfr/kfr/build/fft-benchmark/benchmark.py", line 73, in collect_data
    output = subprocess.check_output([executable] + [str(size) for size in sizes], stderr=subprocess.STDOUT).splitlines()
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/localhost/madhu/kfr/kfr/build/fft-benchmark/bin/fft_benchmark_kfr_float'

Can you please help with the required steps to generate mflops data by running the benchmark script? Thanks in advance.

Best,
Madhu

**Comment by dancasarin** [comment]
Benchmark code has been rewritten from scratch. Could you try this with the latest version?
