### ISSUE TITLE
Preprocessing variable __arm64__ not standard

### ISSUE THREAD

**Issue by meiyasan** [kfrlib/fft-benchmark#8]
Hi,

The identifier `__arm64__` is not a predefined macro in the C or C++ standard, so its behavior is not guaranteed across different compilers and architectures. For ARM64 architecture, you might want to use `__aarch64__` instead.

https://github.com/kfrlib/fft-benchmark/blame/c91027c9f2ed2c4375fe7c504bd56023a06e9312/src/benchmark.hpp#L177

**Comment by dancasarin** [comment]
Hi,

Good catch. Thank you.

Fixed in `master`
